export { default as Home } from './Home';
export { default as Yoga } from './Yoga';
export { default as Tests } from './Tests';
export { default as Sounds } from './Sounds';
export { default as Motivation } from './Motivation';
export { default as SignIn } from './SignIn';
export { default as SignUp } from './SignUp';
export { default as Chat } from './Chat';
export { default as Books } from './Books';
export { default as Pictures } from './Pictures';
export { default as Psychologists } from './Psychologists';
export { default as AboutAs } from './AboutAs';
export {default as Payment} from './Payment';
